### ISSUE TITLE
Ignore motion effect if reduce motion is turned on

### ISSUE THREAD

**Issue by BasThomas** [GitHawkApp/ContextMenu#15]
If a user turns on reduce motion, we should ignore the motion effects.

If we want to keep the consumer of the library in charge, we should add a recommendation in the header docs and in the example code.

We can also choose to ignore motion on the library level - in which case we should update the header docs to reflect it.

**Comment by rnystrom** [comment]
I say we make the lib handle this and promote best practices.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
