### ISSUE TITLE
tint-dimming behind ContentMenu

### ISSUE THREAD

**Issue by palmin** [GitHawkApp/ContextMenu#20]
This is a very nice implementation and I plan to use it in [Working Copy](https://workingcopyapp.com) for switching between branches and file modes. 

Everything behind ContextMenu is dimmed slightly with the overlay, but I'm trying to also dim the tint using the `UIViewTintAdjustmentModeDimmed` mechanism. This makes it much clearer that the ContextMenu has focus.

Do you know of some way to inform UIKit that this should happen?

A regular `modalPresentationStyle = .popover` gives this effect, but I cannot figure out how to achieve this with `modalPresentationStyle = .custom`.

Being really picky about my development tools I'm still waiting for Swift tooling to mature and ported most of ContextMenu to objective-c. Is this something you would like to get back into the project or would you rather not? 

![dim](https://user-images.githubusercontent.com/1230554/37873436-3503d5ec-301d-11e8-938d-8d89db8d48aa.gif)

**Comment by palmin** [comment]
This was the easiest way for me to ask this question and it is not a issue with ContextMenu as such. Feel free to close the issue without a second thought.

**Comment by palmin** [comment]
I found a solution that seems to work. 

Setting `window.tintAdjustmentMode = UIViewTintAdjustmentModeDimmed` when presenting ContextMenu and resetting to `window.tintAdjustmentMode = UIViewTintAdjustmentModeNormal` when dismissing dims tint colors behind ContextMenu while shown but leaves the one inside ContextMenu normal.

I presume UIKit adjusts `tintAdjustmentMode` on presented view controllers.

**Comment by rnystrom** [comment]
@palmin this is awesome! I might add this as a config param then since it looks pretty easy and has a really cool effect!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
