### ISSUE TITLE
Unable to find a specification for `ContextMenu`

### ISSUE THREAD

**Issue by mikengyn** [GitHawkApp/ContextMenu#21]
I get this when trying to install the Pod

`Unable to find a specification for 'ContextMenu'`

doing this will work however 
`pod 'ContextMenu', git: 'https://github.com/GitHawkApp/ContextMenu.git'`

**Comment by marcuswu0814** [comment]
Maybe you can try `pod repo update`.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rnystrom** [comment]
Double checked that the pod exists in trunk. Can you try updating and let us know?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikengyn** [comment]
ah that did the trick, thanks again!
