### ISSUE TITLE
ContextMenuDelegate is missing

### ISSUE THREAD

**Issue by Daxito** [GitHawkApp/ContextMenu#22]
I installed the POD (  pod 'ContextMenu') but it is missing ContextMenuDelegate, am I missing something ?

Thanks!

**Comment by rnystrom** [comment]
In the example or in your project?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Daxito** [comment]
If I use the example as is, it is fine, if in the example I use (notice I removed the local path):
pod 'ContextMenu' 
Then I get error.

Since in my project I do not use the path but just "pod 'ContextMenu' " then I get the error.

Thanks!

**Comment by rnystrom** [comment]
@Daxito can you try `pod update ContextMenu`? Or `pod deintegrate && pod install` to wipe pods and reinstall?

I just setup a dummy app and it builds fine.

[Test.zip](https://github.com/GitHawkApp/ContextMenu/files/1890159/Test.zip)

**Comment by Daxito** [comment]
In your test you did not try to implement ContextMenuDelegate, try that and you will the error, that file does not exist.
Thank you for looking into this!

**Comment by rnystrom** [comment]
Oops! Found it. Hadn't pulled + pushed my `master` branch, duh. Just pushed the lib to version 0.2.0.
