### ISSUE TITLE
Wrong present and dismiss position 

### ISSUE THREAD

**Issue by marcuswu0814** [GitHawkApp/ContextMenu#25]
I'm trying to use ContextMenu on `rightBarButtonItem` like this:

```
fileprivate func setupFilterButton() {
    let button = UIButton(type: .system)
    button.addTarget(self, action: #selector(filterButtonClicked), for: .touchUpInside)
    button.setTitle("Filter", for: .normal)
    let item = UIBarButtonItem(customView: button)
        
    navigationItem.rightBarButtonItem = item
}

@objc fileprivate func filterButtonClicked() {
    let viewController = UIViewController()
    viewController.preferredContentSize = CGSize(width: 200, height: 200)
        
    ContextMenu().show(sourceViewController: self,
                       viewController: viewController,
                       sourceView: navigationItem.rightBarButtonItem?.customView,
                       delegate: nil)
}
```

Present worked well, but dismiss animation look like had some problem.

And I also used it in IGListKit's method `didSelectItem(at:)`

```
override func didSelectItem(at index: Int) {
    guard let cell = collectionContext?.cellForItem(at: index, sectionController: self) else {
        fatalError()
    }
        
    let viewController = UIViewController()
    viewController.preferredContentSize = CGSize(width: 200, height: 200)
        
    ContextMenu().show(sourceViewController: self.viewController!,
                       viewController: viewController,
                       sourceView: cell,
                       delegate: nil)
}
```

Both present and dismiss position weird.

Any tips for me to fix this issue?

![ezgif-4-7d370162d8](https://user-images.githubusercontent.com/6396757/40044834-2d74d9aa-585b-11e8-9282-d769b380b19b.gif)

**Comment by rnystrom** [comment]
@marcuswu0814 wo! That is weird. Do you have that sample project that I could poke around at? 

If you want to help debug that would be so helpful 🙏 It looks like an issue with tracking the source views position on dismiss.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by marcuswu0814** [comment]
[Here](https://github.com/marcuswu0814/ContextMenuBug) is a reproduce project. Maybe I can try to trace the issue but may spend some time. 😅

**Comment by rnystrom** [comment]
@marcuswu0814 you need to use the singleton menu. You're initializing the `ContextMenu()` every time and it isn't retained. So when the controller is dismissed there is no dismiss transition delegate. Changing `ContextMenu()` to `ContextMenu.shared` will fix it for you.
