### ISSUE TITLE
Can't use custom cell in TableView

### ISSUE THREAD

**Issue by VladK9** [GitHawkApp/ContextMenu#52]
App crash with custom cell (ImageView with Label)

**Comment by manuelsBTS** [comment]
Probably you are not register the nib class properly

**Comment by rizwankce** [comment]
@VladK9 Do you have any sample project which can be reproducible?

**Comment by VladK9** [comment]
@rizwankce No, but I'm try later

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
